### PR TITLE
Remove entity_type references

### PR DESCRIPTION
**Pull request by SamMacy**
# Pull request questions

## Which issue does this address

Issue number: #26

The reference at line 365 doesn't have a "RECORD_TYPE" with it, just need confirmation on that, everything else looks good.

### CODE REVIEW

**Comment by SamMacy** [comment]
Pause on this, I've missed some things

**Comment by SamMacy** [comment]
Ok, it should be a go now.

**Review by jbutcher21 — CHANGES_REQUESTED** [review]
All good except the change of rowData['businessEntityType'].  That is their field that we map from, not an attribute we are mapping to.

**Review by jbutcher21 — CHANGES_REQUESTED** [review]
Sorry, I missed one more item.   please remove the 2 addRecordType from the dnb_config_updates.g2c file.   We went from the controlled entity_type attribute to an uncontrolled record_type attribute.

**Review by jbutcher21 — APPROVED** [review]

**Pull request merged**
